export const eventTypes = {
    jardin: [
        "Bodas",
        "Quinceaños",
        "Bautizos",
        "Cumpleaños",
        "Picnics corporativos",
        "Eventos al aire libre",
        "Fiestas de compromiso",
        "Reuniones familiares",
    ],
    salonInfantil: [
        "Fiestas de cumpleaños infantiles",
        "Bautizos",
        "Fiestas temáticas",
        "Show de payasos o magos",
        "Eventos escolares",
        "Tardes de cine para niños",
        "Talleres infantiles",
    ],
    salon: [
        "Conferencias",
        "Seminarios",
        "Reuniones empresariales",
        "Bodas",
        "Quinceaños",
        "Fiestas de fin de año",
        "Eventos sociales",
        "Presentaciones de producto",
    ],
    hacienda: [
        "Bodas",
        "Eventos corporativos",
        "Fiestas de gala",
        "Fiestas temáticas",
        "Quinceaños",
        "Bautizos",
        "Reuniones familiares grandes",
        "Sesiones fotográficas",
    ],
    terraza: [
        "Fiestas al aire libre",
        "Asados o BBQs",
        "Reuniones familiares o de amigos",
        "Eventos privados",
        "Cumpleaños",
        "Brunchs",
        "Fiestas al atardecer (sunset parties)",
        "Eventos de networking",
    ],
};